server:
  port: 8082


spring:
  datasource:
    url: jdbc:h2:mem:group-service
  cloud:
    discovery:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop