server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:contribution-service
  cloud:
    discovery:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    prefer-ip-address: true